In [11]:
import torch
import numpy as np
import matplotlib.pyplot as plt

d:\anaconda\envs\pytorch\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


# numpy基础
数据处理库。核心是多维数组NDarray
底层使用C实现，效率高。

## NDArray
numpy中最重要的类。多维数据包装器

多维数组的创建、修改以及多维数组的属性

### 创建
从数组创建或使用内置函数

In [27]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.zeros([2, 2, 3], dtype = np.float32)
arr3 = np.ones([2, 2])
print(arr1, type(arr1))
print(arr2)
print(arr3)

[1 2 3 4 5] <class 'numpy.ndarray'>
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
[[1. 1.]
 [1. 1.]]


### 修改
主要包括维度变换和拼接

In [50]:
arr1 = np.zeros([1, 1, 4],  dtype=np.int32)
arr2 = np.ones([5, 1, 4], dtype=np.int32)
arr = np.concatenate([arr1, arr2], axis=0)
print('concatenate:', arr)

print('expand1:', np.expand_dims(arr1, 3))
print('expand2', arr2[ :, :, np.newaxis, :])

concatenate: [[[0 0 0 0]]

 [[1 1 1 1]]

 [[1 1 1 1]]

 [[1 1 1 1]]

 [[1 1 1 1]]

 [[1 1 1 1]]]
expand1: [[[[0]
   [0]
   [0]
   [0]]]]
expand2 [[[[1 1 1 1]]]


 [[[1 1 1 1]]]


 [[[1 1 1 1]]]


 [[[1 1 1 1]]]


 [[[1 1 1 1]]]]


### 获取数组属性

In [43]:
arr = np.array([[1, 1, 4, 5, 1, 4], [1, 9, 1, 9, 8, 10]])
print('size:', arr.size)
print('shape:', arr.shape)

size: 12
shape: (2, 6)


### 切片和筛选
切片和python list一致



In [52]:
arr = np.array([[1, 1, 4, 5, 1], 
                [4, 1, 9, 1, 9],
                [8, 1, 0, 1, 1], 
                [4, 5, 1, 4, 1], 
                [9, 1, 9, 8, 10]])

print('single choose')
print(arr[1])
print(arr[1, 0])
print(arr[[1, 0], [2, 3]])

print('slice')
print(arr[:2, :3])

print('filter')
print(arr>5)
print(arr[arr>7])



single choose
[4 1 9 1 9]
4
[9 5]
slice
[[1 1 4]
 [4 1 9]]
filter
[[False False False False False]
 [False False  True False  True]
 [ True False False False False]
 [False False False False False]
 [ True False  True  True  True]]
[ 9  9  8  9  9  8 10]


### np.where
按条件选择、替换数据

In [53]:
condition = arr>5
print(np.where(condition, -1, arr))
print(np.where(condition, -1, 2))
rra = -arr
print(np.where(condition, arr, rra))

[[ 1  1  4  5  1]
 [ 4  1 -1  1 -1]
 [-1  1  0  1  1]
 [ 4  5  1  4  1]
 [-1  1 -1 -1 -1]]
[[ 2  2  2  2  2]
 [ 2  2 -1  2 -1]
 [-1  2  2  2  2]
 [ 2  2  2  2  2]
 [-1  2 -1 -1 -1]]
[[-1 -1 -4 -5 -1]
 [-4 -1  9 -1  9]
 [ 8 -1  0 -1 -1]
 [-4 -5 -1 -4 -1]
 [ 9 -1  9  8 10]]
